### ISSUE TITLE
why do apps installed with appinst crash upon opening

### ISSUE THREAD

**Issue by aupsham** [akemin-dayo/AppSync#169]
iOS version 15.7.6
iphone 7
After installing the DVIA testing application using appsync unified , applications crashes.
I am using Palar1an jailbreak with rootful mode still this issue ,
is this issue from the Appsync or from the device dont know still need to figure out y this happens, 
cuz same thing happened with iphone 8 , ios version 16.2 .

**Comment by akemin-dayo** [comment]
Please try updating to appinst 1.2 and seeing if it works.

I was able to install the DVIA IPA on my test device.

```console
YuriaPod-N112:~ mobile$ appinst DVIA-v2-swift.ipa 
appinst (App Installer)
Copyright (C) 2014-2023 Karen/あけみ
** PLEASE DO NOT USE APPINST FOR PIRACY **
Initialising appinst installation session ID EURiQfiUOLpBE1e5rrYNKRp86tBEQOtz (PID 14492)…
Installing "com.highaltitudehacks.DVIAswiftv2"…
Cleaning up appinst session ID EURiQfiUOLpBE1e5rrYNKRp86tBEQOtz (PID 14492)…
Deleting temporary directory…
Successfully installed "com.highaltitudehacks.DVIAswiftv2"!
```

**Comment by akemin-dayo** [comment]
The crash is occurring because the DVIA-v2 IPA is not fakesigned correctly.

AppSync Unified (and appinst) have correctly installed the app, it's just that the app is being killed by iOS instantaneously due to codesigning issues.

A user-friendly solution to fixing incorrectly signed IPAs is to use something like [iOS App Signer](https://iosappsigner.com/) (※ requires macOS) and re-sign it yourself using either ad-hoc signing or your own (free) certificate.

If you know your way around iOS (which you probably do, if you're looking at an app like DVIA), then you can simply do this in a Terminal session:

```bash
# Get the installed app's sandbox UUID path
find /var/containers/Bundle/Application | grep "DVIA-v2.app/DVIA-v2"
# Change directories to it
cd /var/containers/Bundle/Application/APP_SANDBOX_UUID_HERE/DVIA-v2.app
# Resign the main binary while keeping existing entitlements intact
ldid -s DVIA-v2
```
